--<ScriptOptions statementTerminator=";"/>

CREATE TABLE "DB2ADMIN"."CREDENTIAL" (
		"USER_ID" VARCHAR(100) NOT NULL,
		"PASSWORD" VARCHAR(32) NOT NULL,
		"SALT" VARCHAR(32) NOT NULL
	);

CREATE UNIQUE INDEX "DB2ADMIN"."CC1354499694388" ON "DB2ADMIN"."CREDENTIAL" ("USER_ID" ASC);

ALTER TABLE "DB2ADMIN"."CREDENTIAL" ADD CONSTRAINT "CC1354499694388" PRIMARY KEY ("USER_ID");

